export default [
    {
        id: 0,
        imgSrc: "./images/the_weeknd_capa.jpg",
        wallpaperSrc: "./images/the_weeknd_wallpaper.jpg",
        src: "./audios/The Weeknd/1 - The Weeknd - After Hours.mp3",
        name: "After Hours",
        author: "The Weeknd",
    },
    {
        id: 1,
        imgSrc: "./images/the_weeknd_capa.jpg",
        wallpaperSrc: "./images/the_weeknd_wallpaper.jpg",
        src: "./audios/The Weeknd/2 - The Weeknd - Blinding Lights.mp3",
        name: "Blinding Lights",
        author: "The Weeknd",
    },
    {
        id: 2,
        imgSrc: "./images/the_weeknd_capa.jpg",
        wallpaperSrc: "./images/the_weeknd_wallpaper.jpg",
        src: "./audios/The Weeknd/3 - The Weeknd - Call Out My Name.mp3",
        name: "Call Out My Name",
        author: "The Weeknd",
    },
    {
        id: 3,
        imgSrc: "./images/the_weeknd_capa.jpg",
        wallpaperSrc: "./images/the_weeknd_wallpaper.jpg",
        src: "./audios/The Weeknd/4 - The Weeknd - The Hills.mp3",
        name: "The Hills",
        author: "The Weeknd",
    },
    {
        id: 4,
        imgSrc: "./images/the_weeknd_capa.jpg",
        wallpaperSrc: "./images/the_weeknd_wallpaper.jpg",
        src: "./audios/The Weeknd/5 - The Weeknd - Die For You.mp3",
        name: "Die For You",
        author: "The Weeknd",
    },
    {
        id: 5,
        imgSrc: "./images/the_weeknd_capa.jpg",
        wallpaperSrc: "./images/the_weeknd_wallpaper.jpg",
        src: "./audios/The Weeknd/6 - The Weeknd - Starboy ft. Daft Punk.mp3",
        name: "Starboy ft. Daft Punk",
        author: "The Weeknd",
    },
    {
        id: 6,
        imgSrc: "./images/the_weeknd_capa.jpg",
        wallpaperSrc: "./images/the_weeknd_wallpaper.jpg",
        src: "./audios/The Weeknd/7 - The Weeknd - Reminder.mp3",
        name: "Reminder",
        author: "The Weeknd",
    },
    {
        id: 7,
        imgSrc: "./images/the_weeknd_capa.jpg",
        wallpaperSrc: "./images/the_weeknd_wallpaper.jpg",
        src: "./audios/The Weeknd/8 - The Weeknd - I Feel It Coming ft. Daft Punk.mp3",
        name: "I Feel It Coming ft. Daft Punk",
        author: "The Weeknd",
    },
    {
        id: 8,
        imgSrc: "./images/the_weeknd_capa.jpg",
        wallpaperSrc: "./images/the_weeknd_wallpaper.jpg",
        src: "./audios/The Weeknd/9 - The Weeknd - Heartless.mp3",
        name: "Heartless",
        author: "The Weeknd",
    },
    {
        id: 9,
        imgSrc: "./images/the_weeknd_capa.jpg",
        wallpaperSrc: "./images/the_weeknd_wallpaper.jpg",
        src: "./audios/The Weeknd/10 - The Weeknd - The Morning.mp3",
        name: "The Morning",
        author: "The Weeknd",
    },
    {
        id: 10,
        imgSrc: "./images/the_neighbourhood_capa.jpeg",
        wallpaperSrc: "./images/the_neighbourhood_wallpaper.jpg",
        src: "./audios/The Neighbourhood/1 - The Neighbourhood - Fallen Star.mp3",
        name: "Fallen Star",
        author: "The Neighbourhood",
    },
    {
        id: 11,
        imgSrc: "./images/the_neighbourhood_capa.jpeg",
        wallpaperSrc: "./images/the_neighbourhood_wallpaper.jpg",
        src: "./audios/The Neighbourhood/2 - The Neighbourhood - Flawless.mp3",
        name: "Flawless",
        author: "The Neighbourhood",
    },
    {
        id: 12,
        imgSrc: "./images/the_neighbourhood_capa.jpeg",
        wallpaperSrc: "./images/the_neighbourhood_wallpaper.jpg",
        src: "./audios/The Neighbourhood/3 - The Neighbourhood - Leaving Tonight.mp3",
        name: "Leaving Tonight",
        author: "The Neighbourhood",
    },
    {
        id: 13,
        imgSrc: "./images/the_neighbourhood_capa.jpeg",
        wallpaperSrc: "./images/the_neighbourhood_wallpaper.jpg",
        src: "./audios/The Neighbourhood/4 - The Neighbourhood - Scary Love.mp3",
        name: "Scary Love",
        author: "The Neighbourhood",
    },
    {
        id: 14,
        imgSrc: "./images/the_neighbourhood_capa.jpeg",
        wallpaperSrc: "./images/the_neighbourhood_wallpaper.jpg",
        src: "./audios/The Neighbourhood/5 - The Neighbourhood - Sweater Weather.mp3",
        name: "Sweater Weather",
        author: "The Neighbourhood",
    },
    {
        id: 15,
        imgSrc: "./images/the_neighbourhood_capa.jpeg",
        wallpaperSrc: "./images/the_neighbourhood_wallpaper.jpg",
        src: "./audios/The Neighbourhood/6 - The Neighbourhood - W.D.Y.W.F.M.mp3",
        name: "W.D.Y.W.F.M",
        author: "The Neighbourhood",
    },
    {
        id: 16,
        imgSrc: "./images/lana_del_rey_capa.png",
        wallpaperSrc: "./images/lana_del_rey_capa.png",
        src: "./audios/Lana Del Rey/1 - Lana Del Rey - Born To Die.mp3",
        name: "Born To Die",
        author: "Lana Del Rey",
    },
    {
        id: 17,
        imgSrc: "./images/lana_del_rey_capa.png",
        wallpaperSrc: "./images/lana_del_rey_capa.png",
        src: "./audios/Lana Del Rey/2 - Lana Del Rey - Brooklyn Baby.mp3",
        name: "Brooklyn Baby",
        author: "Lana Del Rey",
    },
    {
        id: 18,
        imgSrc: "./images/lana_del_rey_capa.png",
        wallpaperSrc: "./images/lana_del_rey_capa.png",
        src: "./audios/Lana Del Rey/3 - Lana Del Rey - Cola.mp3",
        name: "Cola",
        author: "Lana Del Rey",
    },
    {
        id: 19,
        imgSrc: "./images/lana_del_rey_capa.png",
        wallpaperSrc: "./images/lana_del_rey_capa.png",
        src: "./audios/Lana Del Rey/4 - Lana Del Rey - Ultraviolence.mp3",
        name: "Ultraviolence",
        author: "Lana Del Rey",
    },
    {
        id: 20,
        imgSrc: "./images/lana_del_rey_capa.png",
        wallpaperSrc: "./images/lana_del_rey_capa.png",
        src: "./audios/Lana Del Rey/5 - Lana Del Rey - Young and Beautiful.mp3",
        name: "Young and Beautiful",
        author: "Lana Del Rey",
    },
    {
        id: 22,
        imgSrc: "./images/we_are_the_people_capa.jpg",
        wallpaperSrc: "./images/we_are_the_people_capa.jpg",
        src: "./audios/Old/1 - Empire Of The Sun - We Are The People.mp3",
        name: "We Are The People",
        author: "Empire Of The Sun",
    },
    {
        id: 23,
        imgSrc: "./images/everybody_wants_to_rule_the_world_capa.jpeg",
        wallpaperSrc: "./images/everybody_wants_to_rule_the_world_capa.jpeg",
        src: "./audios/Old/2 - Tears for Fears - Everybody Wants To Rule The World.mp3",
        name: "Everybody Wants To Rule The World",
        author: "Tears for Fears",
    },
    {
        id: 24,
        imgSrc: "./images/toto_capa.jpeg",
        wallpaperSrc: "./images/toto_capa.jpeg",
        src: "./audios/Old/3 - TOTO - Hold The Line.mp3",
        name: "Hold The Line",
        author: "TOTO",
    },
    {
        id: 26,
        imgSrc: "./images/young_turks_capa.jpg",
        wallpaperSrc: "./images/young_turks_capa.jpg",
        src: "./audios/Old/4 - Rod Stewart - Young Turks.mp3",
        name: "Young Turks",
        author: "Rod Stewart",
    }
]